//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Appointment
    {
        public int Id { get; set; }


        [Display(Name = "زمان شروع")]
        public DateTime StartTime { get; set; }

        [Display(Name = "زمان پایان")]
        public DateTime EndTime { get; set; }

        
        [UIHint("DateTime")]
        //[RegularExpression(@"^(13\d{2}|[1-9]\d)/(1[012]|0?[1-9])/([12]\d|3[01]|0?[1-9]) ([01][0-9]|2[0-3]):([0-5]?[0-9])$", ErrorMessage = "تاریخ ثبت را بدرستی وارد کنید")]
        [Display(Name = "تاریخ")]
        public DateTime myDate { get; set; }


        public String start { get; set; }

        [Display(Name = "تاریخ رزرو")]
        public DateTime BookDate { get; set; }

        [Display(Name = "سرویس")]
        public int ServiceId { get; set; }

        [Display(Name = "نام کاربر")]
        public int UserId { get; set; }
        public bool isReserved { get; set; }


        [Display(Name = "توضیحات")]
        public string Description { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
