//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Appointments = new HashSet<Appointment>();
            this.JobCorps = new HashSet<JobCorp>();
            this.Jobs = new HashSet<Job>();
        }



        public int Id { get; set; }

        [Required(ErrorMessage = "وارد کردن ایمیل الزامی است")]
        [EmailAddress(ErrorMessage = "ایمیل درست وارد کنید")]
        [StringLength(32)]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "ایمیل")]
        public string Email { get; set; }



        [Required(ErrorMessage = "وارد کردن رمز عبور الزامی است")]
        [DataType(DataType.Password)]
        [Display(Name = "رمز عبور")]
        [StringLength(64, ErrorMessage = "رمز عبور باید حداقل 6 کاراکتر باشد", MinimumLength = 6)]
        public string Password { get; set; }


        [DataType(DataType.PhoneNumber)]
        [Display(Name = "شماره موبایل")]

        [Required(ErrorMessage = "وارد کردن شماره موبایل الزامی است")]
        [StringLength(11)]
        //[Remote("doesPhoneNumberExist", "User", HttpMethod = "POST", ErrorMessage = "Phone Number already exists. Please enter a different phne number.")]
        //^[01]?[- .]?(\([2-9]\d{2}\)|[2-9]\d{2})[- .]?\d{3}[- .]?\d{4}$
        [RegularExpression(@"^09(1[0-9]|3[1-9]|2[1-9])-?[0-9]{7}$", ErrorMessage = "شماره موبایل خود را با فرمت زیر وارد کنید: 09127404062")]
        public string Phone { get; set; }


        [Required(ErrorMessage = "این فیلد باید پر شود")]
        [Display(Name = "نام و نام خانوادگی")]
        public string FullName { get; set; }


        [Display(Name = "درباره شما")]
        public string About { get; set; }


        [Display(Name = "شهر")]
        public int CityId { get; set; }


        [Display(Name = "وظیفه")]
        public int UserRoleId { get; set; }

        public String RoleName
        {
            get
            {
                return Enum.GetName(typeof(MyUserRole), (MyUserRole)UserRoleId);
            }
        }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobCorp> JobCorps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
